COMMON_FLAGS="-fomit-frame-pointer -march=native -pipe -O2"
RUSTFLAGS="-C target-cpu=native -C opt-level=3"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

LC_MESSAGES=C.utf8
ACCEPT_LICENSE="*"

USE="wayland dist-kernel policykit networkmanager bluetooth pulseaudio cups alsa clang pgo lto"
VIDEO_CARDS="amdgpu radeonsi nvidia"
