
[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[supertux88]
location = /var/db/repos/supertux88
sync-type = git
sync-uri = https://github.com/gentoo-mirror/supertux88.git

[pentoo]
location = /var/db/repos/pentoo
sync-type = git
sync-uri = https://github.com/gentoo-mirror/pentoo.git

[danidev]
location = /var/db/repos/danidev
sync-type = git
sync-uri = https://github.com/DaniD3v/gentoo-overlay.git
